- name: Install mysql (state=present is optional)
  ansible.builtin.apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: Install PyMySQL
  ansible.builtin.apt:
    name: python3-pymysql
    state: present
  


- name: Start mysql
  ansible.builtin.service:
    name: mysql
    state: started

- name: Create database
  community.mysql.mysql_db:
    name: kaizen
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock


- name: Create database user 
  community.mysql.mysql_user:
    name: hello
    password: world123
    priv: '*.*:ALL'
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock